name: PVPArena
version: '${project.version}'
main: dev.sasukector.pvparena.PVPArena
api-version: 1.17
authors: [ Sasukector ]
description: This is the core plugin for PVPArena
website: https://sasukector.dev
commands:
  game:
    description: Command to manage game
    usage: /game [option]